project_id = "terlzdzxhztuskifhgvg"

[functions.send-booking-notification]
verify_jwt = false

[functions.expire-abandoned-bookings]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.whatsapp-broadcast]
verify_jwt = false

[functions.whatsapp-reminders]
verify_jwt = false
